
export { routerInstitution } from './institucion.route';
export { routerUser } from './user.route';
export { routerAuth } from './auth.route';
export { routerRoles } from './roles.route';
export { routerStaff } from './staff.route';
export { routerTypeStaff } from './typeStaff.route';
export { routerAttendance } from './attendance.route';
export { routerTypeAttendance } from './typeAttendance.route';
export { routerInstitutionStaff } from './institutionStaff.route';
export { routerWorkSchudule } from './workSchudele.route';
export { routerWorkSchuduleIE } from './workSchudeleIE.route';
export { routerBiometric } from './biometric.route';
export { routerReport } from './report.route';
export { routerFile } from './file.route';
export { routerJustification } from './justification.route';
export { routerShift } from './shift.route';
export { routerSearch } from './search.route'
export { routerEmail } from './email.route'
export { routerHolyDay } from './holyDay.route'
